daily_income_expence/account/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register',v.adduser, name='reg'), 
    path('login',v.login_view, name='login'), 
    path('logout',v.logout_view, name='logout'), 
]

daily_income_expence/daily_income_expence/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('acc-',include(('account.urls','account'), namespace='account')),
    path('',include(('income.urls','income'), namespace='income')),
    path('',include(('expense.urls','expense'), namespace='expense')),
]

daily_income_expence/expense/urls.py
from django.contrib import admin
from django.urls import path
from. import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expense',v.addexpense, name='exp'),
    path('expense_list',v.expense_list, name='explist'),
    path('delete/<int:id>',v.delete_expense, name='delete'),
    path('expense_search',v.expense_search, name='expense_search'),
    path('ext/<str:extc>',v.sort_by_expense_type, name='ext'),
    
]

daily_income_expence/income/urls.py
from django.contrib import admin
from django.urls import path
from. import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('income',v.addincome, name='inc'),
    path('income_list',v.income_list, name='list'),
    path('delete/<int:id>',v.delete_income, name='delete'),
    path('income_search',v.income_search, name='income_search'),
]

daily_income_expence/account/models.py
from django.db import models

from django import forms

class LoginForm(forms.Form):
    username=forms.CharField(max_length=30)
    password=forms.CharField(max_length=30,widget=forms.PasswordInput)

daily_income_expence/expense/models.py
from django.db import models
from django.contrib.auth.models import User

class Expense(models.Model):
    expense=models.IntegerField()
    expense_type=models.CharField(max_length=30)
    expense_date=models.DateField()
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table='expense'


from django import forms

class expenseForm(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'
        

daily_income_expence/income/models.py
from django.db import models
from django.contrib.auth.models import User

class Income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    income_date=models.DateField()
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table='income'

    # def __str__(self):
        # return self.user 


from django import forms

class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields='__all__'

daily_income_expence/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def home(request):
    context={'bal':get_balance(request)}
    return render(request, 'home.html',context)

def adduser(request):
    if request.method == 'POST':
        f=UserCreationForm(request.POST)
        f.save()
        return redirect('/') 
    else:
        f = UserCreationForm
        context = {'form': f}
        return render(request, 'adduser.html', context)
    
from .models import LoginForm
from django.contrib.auth import authenticate,login,logout

def login_view(request):
    if request.method == 'POST':
        uname = request.POST.get('username')    
        passw = request.POST.get('password')   

        user= authenticate(request, username=uname,password=passw)
        if user is not None:

            request.session['uid']=user.id
            login(request,user)
            return redirect('/')
        else:
            f=LoginForm
            context={'form':f}
            return render(request,'login.html',context)
        
    else:
        f=LoginForm
        context={'form':f}
        return render(request,'login.html',context)
    
def logout_view(request):
    logout(request)
    return redirect('/')

from income.models import Income
from expense.models import Expense

def get_balance(request):
    uid=request.session.get('uid')
    incl=Income.objects.filter(user=uid)
    expl=Expense.objects.filter(user=uid)

    total_income=0
    total_expense=0

    for i in incl:
        total_income=total_income+i.income
    for i in expl:
        total_expense=total_expense+i.expense
    
    return total_income-total_expense

daily_income_expence/expense/views.py
from django.shortcuts import render,redirect

from account.views import get_balance

from .models import expenseForm,Expense
from django.contrib.auth.models import User


def addexpense(request):
    uid=request.session.get('uid')
    if request.method == 'POST':
        # f=expenseForm(request.POST)
        expense=request.POST.get('expense')
        if get_balance(request)>int(expense):
            expense_type=request.POST.get('expense_type')
            expense_date=request.POST.get('expense_date')
            description=request.POST.get('description')
            exp=Expense()
            exp.expense=expense
            exp.expense_type=expense_type
            exp.expense_date=expense_date
            exp.description=description
            exp.user=User.objects.get(id=uid)
            exp.save()
            return redirect('/') 
        else:
            f=expenseForm
            context={'form':f,'exp_msg':'Insufficient balance bhai paise kamale'}
            return render(request,'addexpense.html',context)
    else:
        f = expenseForm
        context = {'form': f}
        return render(request, 'addexpense.html', context)
    

def expense_list(request):
    uid=request.session.get('uid')
    explist=Expense.objects.filter(user=uid)
    expt=set()
    for i in explist:
        expt.add(i.expense_type)
    context={'expe':explist, 'expt':expt}
    return render(request, 'expense_list.html', context)

def delete_expense(request,id):
    exp=Expense.objects.get(id=id)
    exp.delete()
    return redirect('/')

def expense_search(request):
    uid=request.session.get('uid')
    srch=request.POST.get('srch')
    expe=Expense.objects.filter(user=uid,description__contains=srch)
    context={'expe':expe}
    return render(request, 'expense_list.html', context)

def sort_by_expense_type(request,extc):
    uid=request.session.get('uid')
    explist=Expense.objects.filter(user=uid)
    expt=set()
    for i in explist:
        expt.add(i.expense_type)
    # for data based on category
    explist=Expense.objects.filter(user=uid,expense_type=extc)

    context={'expe':explist,'expt':expt}
    return render(request, 'expense_list.html', context)

daily_income_expence/income/views.py
from django.shortcuts import render,redirect
from .models import Income, IncomeForm
from django.contrib.auth.models import User


def addincome(request):
    uid=request.session.get('uid')
    if request.method == 'POST':
        # f=IncomeForm(request.POST)
        income=request.POST.get('income')
        income_type=request.POST.get('income_type')
        income_date=request.POST.get('income_date')
        description=request.POST.get('description')
        inc=Income()
        inc.income=income
        inc.income_type=income_type
        inc.income_date=income_date
        inc.description=description
        inc.user=User.objects.get(id=uid)
        inc.save()
        return redirect('/') 
    else:
        f = IncomeForm
        context = {'form': f}
        return render(request, 'addincome.html', context)
    
def income_list(request):
    uid=request.session.get('uid')
    inclist=Income.objects.filter(user=uid)
    context={'incl':inclist}
    return render(request, 'income_list.html', context)

def delete_income(request,id):
    inc=Income.objects.get(id=id)
    inc.delete()
    return redirect('/')

def income_search(request):
    uid=request.session.get('uid')
    srch=request.POST.get('srch')
    incl=Income.objects.filter(user=uid,description__contains=srch)
    context={'incl':incl}
    return render(request, 'income_list.html', context)

daily_income_expence/account/templates/adduser.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>this is registration form</h1>


<form method="post">
    {%csrf_token%}
    <table border="1">
    {{form.as_table}}
    <tr>
        <td><input type="submit" value="save"></td>
        <td><input type="reset" value="reset"></td>
    </tr>
    </table>
</form>
{%endblock%}

daily_income_expence/account/templates/home.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>daily Income Expense project</h1>
{%if user.is_authenticated%}
    <h2 style="color:black">Welcome : {{user}}</h2>
    <h2 style="color:black">Total Balance : {{bal}}</h2>
{%endif%}
{%endblock%}

daily_income_expence/account/templates/login.html
{%extends 'sidebar.html'%}
{%block body%}
<form method="post">
    {%csrf_token %}
    <table border="1">
        {{form.as_table}}
        <tr>
            <td><input type="submit" value="save"></td>
            <td><input type="reset" value="reset"></td>
        </tr>
    </table>
</form>
{%endblock%}

daily_income_expence/account/templates/sidebar.html
{%load static%}
<link rel="stylesheet" href="{%static 'css/style.css'%}">

<div class="side">
    <h2><a href="/">Home</a></h2>
    {% if user.is_authenticated %}
    <h2><a href="">Edit_Profile</a></h2>
    <h2><a href="{%url 'income:inc'%}">add_Income</a></h2>
    <h2><a href="{%url 'expense:exp'%}">Add_expense</a></h2>
    <h2><a href="{%url 'income:list'%}">Income_list</a></h2>
    <h2><a href="{%url 'expense:explist'%}">Expense_list</a></h2>
    <h2><a href="{%url 'account:logout'%}">Logout</a></h2>

    {%else%}
    
    <h2><a href="{%url 'account:reg'%}">Register</a></h2>

    <h2><a href="{%url 'account:login'%}">Login</a></h2>
    
    {%endif%}
    
    <h2><a href="">AboutUs</a></h2>

</div>

<div class="main">
    {%block body%}
    {%endblock%}
</div>
<style>
    .main{
        margin-left: 10%;
    }
        </style>

daily_income_expence/expense/templates/addexpense.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>please Add Your expense</h1>

{% if exp_msg %}
<h1 style="color: grey;">{{ exp_msg }}</h1>
{%endif%}

<form method="post">
    {%csrf_token%}
    <table border="1">
    <tr>
    <th><label for="id_expense">Expense:</label></th>
    <td>
      
      <input type="number" name="expense" required id="id_expense">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_expense_type">Expense type:</label></th>
    <td>
      
      <input type="text" name="expense_type" maxlength="30" required id="id_expense_type">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_expense_date">Expense date:</label></th>
    <td>
      
      <input type="date" name="expense_date" required id="id_expense_date">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_description">Description:</label></th>
    <td>
      
      <textarea name="description" cols="40" rows="10" maxlength="300" required id="id_description">
</textarea>
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_user">User:</label></th>
    <td><input type="text" name="uid" value="{{user}}"></td>

  </tr>
    <tr>
        <td><input type="submit" value="save"></td>
        <td><input type="reset" value="reset"></td>
    </tr>
    </table>
</form>
{%endblock%}

daily_income_expence/expense/templates/expense_list.html
{%extends 'sidebar.html'%}
{%block body%}
<form method="post" action="{%url 'expense:expense_search'%}">
    {%csrf_token%}
    <textarea name="srch" id="" cols="60" rows="3"></textarea>
    <input type="submit" value="search">
</form>
{%if expe%}
<table border="1">
    <tr>
        <th>Id</th>
        <th>expense</th>
        <th>expense_type</th>
        <th>expense_date</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>
    {%for i in expe%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.expense}}</td>
        <td>{{i.expense_type}}</td>
        <td>{{i.expense_date}}</td>
        <td><textarea name="" id="" cols="30">{{i.description}}</textarea></td>
        <td>{{i.user}}</td>
        <td><a href="{%url 'expense:delete' i.id%}">Delete</a></td>
        <td><a>Edit</a></td>
    </tr>
    {%endfor%}
</table>
{%else%}
<h1>no records found.......</h1>
{%endif%}
<style>
    .rside{
        width: 195px;
        height: 100%;
        background-color: grey;
        position: fixed;
        top: 0%;
        right: 0%;
    }
    h3{
        margin: 10px;
        padding: 10px;
    }
    h2{
        margin-left: 10px;
    }
</style>
<div class="rside">
    <h2>sort by expense type</h2>
    <h3><a href="{%url 'expense:explist'%}">ALL</a></h3>
    {%for i in expt%}
    <h3><a href="{%url 'expense:ext' i %}">{{i}}</a></h3>
    {%endfor%}
</div>
{%endblock%}

daily_income_expence/income/templates/addincome.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>please Add Your Income</h1>
<form method="post">
  {%csrf_token%}
    <table border="1">
    <tr>
    <th><label for="id_income">Income:</label></th>
    <td>
      
      <input type="number" name="income" required id="id_income">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_income_type">Income type:</label></th>
    <td>
      
      <input type="text" name="income_type" maxlength="30" required id="id_income_type">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_income_date">Income date:</label></th>
    <td>
      
      <input type="date" name="income_date" required id="id_income_date">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_description">Description:</label></th>
    <td>
      
      <textarea name="description" cols="40" rows="10" maxlength="300" required id="id_description">
</textarea>
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_user">User:</label></th>
    <td><input type="text" name="uid" value="{{user}}"></td>
  </tr>
    <tr>
        <td><input type="submit" value="save"></td>
        <td><input type="reset" value="reset"></td>
    </tr>
    </table>
</form>

{%endblock%}

daily_income_expence/income/templates/income_list.html
{%extends 'sidebar.html'%}
{%block body%}
<form method="post" action="{%url 'income:income_search'%}">
    {%csrf_token%}
    <textarea name="srch" id="" cols="60" rows="3"></textarea>
    <input type="submit" value="search">
</form>
<table border="1">
    <tr>
        <th>Id</th>
        <th>income</th>
        <th>income_type</th>
        <th>income_date</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>
    {%for i in incl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.income_type}}</td>
        <td>{{i.income_date}}</td>
        <td><textarea name="" id="" cols="30">{{i.description}}</textarea></td>
        <td>{{i.user}}</td>
        <td><a href="{%url 'income:delete' i.id%}">Delete</a></td>
        <td><a>Edit</a></td>
    </tr>
    {%endfor%}
</table>
{%endblock%}